# Generated by Django 2.1.5 on 2019-04-04 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jaar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jaar', models.CharField(default='2019', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weekstaat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maandag', models.FloatField(blank=True, null=True)),
                ('dinsdag', models.FloatField(blank=True, null=True)),
                ('woensdag', models.FloatField(blank=True, null=True)),
                ('donderdag', models.FloatField(blank=True, null=True)),
                ('vrijdag', models.FloatField(blank=True, null=True)),
                ('zaterdag', models.FloatField(blank=True, null=True)),
                ('zondag', models.FloatField(blank=True, null=True)),
                ('jaar', models.ForeignKey(default=2019, on_delete=django.db.models.deletion.CASCADE, to='weekstaat.Jaar')),
                ('week', models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='weekstaat.Week')),
                ('werknemer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekstaat_werknemer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
