# Generated by Django 2.0.2 on 2019-04-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organisatie', models.CharField(max_length=145)),
                ('tussenpersoon', models.CharField(blank=True, max_length=145, null=True)),
                ('tussenpersoon_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),

    ]
