# Generated by Django 2.0.2 on 2019-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20190411_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('actief', 'ACTIEF'), ('concept', 'CONCEPT'), ('niet-actief', 'NIET-ACTIEF')], default='actief', max_length=6),
        ),
    ]
