# Generated by Django 2.1.5 on 2019-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('actief', 'actief'), ('concept', 'concept'), ('non-actief', 'non-actief')], default='actief', max_length=11),
        ),
    ]
