# Generated by Django 2.1.5 on 2019-04-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weekstaat', '0002_auto_20190411_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekstaat',
            name='week',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='weekstaat.Week'),
        ),
    ]
