# Generated by Django 2.2.1 on 2019-05-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weekstaat', '0003_auto_20190430_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekstaat',
            name='week',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='weekstaat.Week'),
        ),
    ]
