# Generated by Django 2.2.1 on 2019-05-06 15:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actie_naam', models.CharField(default='-', max_length=150)),
                ('actie_aanmaakdatum', models.DateField(default=django.utils.timezone.now)),
                ('actie_einddatum', models.DateTimeField(default=datetime.datetime(2019, 5, 7, 15, 4, 58, 210548))),
                ('actie_eindtijdstip', models.TimeField(default='00:00:00')),
                ('actie_gebruiker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
