# Generated by Django 2.2.1 on 2019-05-06 15:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekstaat', '0004_auto_20190506_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factuur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factuurdatum', models.DateField()),
                ('vervaldatum', models.DateField(default=datetime.datetime(2019, 5, 6, 15, 4, 58, 211313))),
                ('totaal_excl_btw', models.FloatField()),
                ('totaal_incl_btw', models.FloatField()),
                ('btw_procent', models.CharField(max_length=10)),
                ('btw_bedrag', models.FloatField()),
                ('weekstaat', models.ManyToManyField(to='weekstaat.Weekstaat')),
                ('werknemer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
